### ISSUE TITLE
prediction always fail, why and how to fix this? message: "IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"

### ISSUE THREAD

**Issue by yzhu-bnt** [TencentAILabHealthcare/scBERT#32]
Traceback (most recent call last):
  File "/home/yzhu/.conda/envs/scBERT/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/yzhu/.conda/envs/scBERT/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mnt/efs/yzhu/scBERT3/predict.py", line 124, in <module>
    pred_list = label_dict[pred_finals].tolist()
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by daria-cara** [comment]
I had the same issue. As it turns out, `pred_final` is a 0-dim torch.Tensor, making `pred_finals` a list of Tensors. Because `label_dict` is a numpy.ndarray, it is expecting "a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool" [(source)](https://numpy.org/doc/stable/user/basics.indexing.html). In order to convert `pred_final` to an integer, I use `pred_final=pred_final.item()` [(source 1)](https://pytorch.org/docs/stable/generated/torch.Tensor.item.html) [(source 2)](https://www.datascienceweekly.org/tutorials/pytorch-item-convert-a-0-dim-pytorch-tensor-to-a-python-number) before appending it to `pred_finals` in Line 123. This resolved the problem for me.

**Comment by kamisama0101** [comment]
Inserting "pred_final = pred_final.cpu().numpy()" before or after the "if np.amax(np.array(pred_prob.cpu()), axis=-1) < UNASSIGN_THRES:
            novel_indices.append(index)" can also solve this problem. I guess they are two ways to do the same thing.
