### ISSUE TITLE
scBERT on Mouse data

### ISSUE THREAD

**Issue by agroppi** [TencentAILabHealthcare/scBERT#43]
Hi

Hi wantt to use scBERT on mouse single cell data.
In the issue #8 
@TencentAILabHealthcare said : "The scBERT could support other species, by replacing the data for pertaining and fine-tuning. The gene identities should also be changed to those of other species."

Could you be more specific ?  : 
- Where can I find these data ?
- How to run the pretraining and fine tunning on it ?
- "The gene identities should also be changed to those of other species." ==> How is it possible to do that ?

I would greatly appreciate your assistance and guidance.

Thank you for your time and consideration.

Best,

Alexis

**Comment by TencentAILabHealthcare** [comment]
1. Where can I find these data ? 
There are some open-sourced databases of single-cell transcriptome of mouse species (i.e. http://mousebrain.org/). The users could use them or other larger mouse database for pre-training and then use annotated datasets including the cell types of interest for fine-tuning.
2. How to run the pretraining and fine tunning on it ?
Both the pre-training and fine-tuning codes have been released and the users should prepocess the data referring to https://github.com/TencentAILabHealthcare/scBERT/blob/master/preprocess.py. Modify the input gene sequence length of the pretrain and fineutne based on your prepared mouse data. The class number should also be modified according to your cell type number.
3. "The gene identities should also be changed to those of other species." ==> How is it possible to do that ?
You could use the original BERT's position embedding instead of gene2vec since perhaps there is no biological prior embedding for mouse data. The model could also be run. The pos_emb argument of the pretrain.py could be set as False for such propose.

**Comment by GuangminZheng** [comment]
Where I can find the original BERT's position embedding???
